<?php
$z[0]=Array("list","<url>\r\n<loc>[field:arcurl function=\"Gmapurl(@me)\"/]</loc>\r\n<lastmod>[field:senddate function=\"strftime('%Y-%m-%d',@me)\"/]</lastmod>\r\n<changefreq>weekly</changefreq>\r\n<priority>0.5</priority>\r\n</url>",2,320);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['typeid']="1";
$z[0][4]['channel']="1";

?>