{dede:specnote imgheight='90' imgwidth='120'
                infolen='300' titlelen='60' col='1' idlist='1570,1569,1568,1567,1566,1565,1564,1563,1562,1561,1560,1559,1558,1557,1556'
                name='默认节点' noteid='default' isauto='0' rownum='100'
                keywords='' typeid='0'}
                <li><a href="[field:arcurl /]" target="_blank">[field:title /]</a></li>
                {/dede:specnote}
