{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist='1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259'
                name='Redis学习教程' noteid='default' isauto='0' rownum='100'
                keywords='' typeid='0'}
                <li >
<a href="[field:arcurl /]" target="_blank">[field:title /]</a><span>[field:pubdate function="MyDate('m.d',@me)"/]</span>
</li>
                {/dede:specnote}
