<?php
$z[0]=Array("specnote","\r\n                <li >\r\n<a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a><span>[field:pubdate function=\"MyDate('m.d',@me)\"/]</span>\r\n</li>\r\n                ",0,531);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259";
$z[0][4]['name']="Redis学习教程";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="100";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>