<?php
$z[0]=Array("specnote","\r\n                <li class=\"list-group-item\"><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n                ",0,447);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="300";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="1570,1569,1568,1567,1566,1565,1564,1563,1562,1561,1560,1559,1558,1557,1556";
$z[0][4]['name']="默认节点";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="100";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>