<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer">
  <div class="container">
    <div class="foot">
      <br/>
                鹏鹏电脑知识网是一家纯计算机技术学习、电脑学习、IT技术学习交流型网站，鹏鹏电脑知识网站所载文章来源于网络，如果不慎侵犯了您的权益，请联系我们删除！站长QQ：657025171<br/>
               <a href="/aboutus.html">关于我们</a> | <a href="/dashiji.html">大事记</a> | <a href="/jiazhiguan.html">网站价值观</a> | <a href="/contactus.html">联系我们</a> | <a href="/submenu.html">网站地图</a> | <a href="/copyright.html">版权声明</a> | <a href="/changwei.html">长尾关键词</a> <br/>
              <?php echo $GLOBALS['cfg_powerby'];  echo $GLOBALS['cfg_beian']; ?><br/>
        
    </div>
  </div>
</div>