<?php
$z[0]=Array("sql","共收藏了[field:c /] 篇技术文章",785,891);
$z[0][4]=array();
$z[0][4]['sql']="select count(*) as c from dede_archives";
$z[1]=Array("global","",997,1022);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel"," \r\n                  <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n                ",2775,2950);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['typeid']="7";
$z[3]=Array("channel"," \r\n                  <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n                ",3280,3455);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['typeid']="8";

?>