<?php
$z[0]=Array("global","",281,307);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",323,360);
$z[1][4]=array();
$z[1][4]['filename']="common.htm";
$z[2]=Array("include","",842,879);
$z[2][4]=array();
$z[2][4]['filename']="header.htm";
$z[3]=Array("list","\r\n\r\n			<div class=\"panel\">				\r\n\r\n		        <div class=\"panel-body\">\r\n\r\n		        	<h3 style=\"background:url('/templets/bootstrap/images/document.png') no-repeat;padding-left:30px;\"><a href='[field:arcurl/]'>[field:title/]</a></h3>\r\n\r\n		            <p>[field:description/]...</p>\r\n\r\n		            <h5>标签：[field:id function=GetTags(@me)/]</h5>\r\n		        </div>\r\n\r\n		    </div>    \r\n\r\n			",1030,1472);
$z[3][4]=array();
$z[3][4]['pagesize']="12";
$z[3][4]['titlelen']="80";
$z[4]=Array("prenext","",1587,1613);
$z[4][4]=array();
$z[4][4]['get']="pre";
$z[5]=Array("prenext","",1651,1678);
$z[5][4]=array();
$z[5][4]['get']="next";
$z[6]=Array("include","",1759,1796);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>