<?php
$z[0]=Array("global","",273,299);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",313,350);
$z[1][4]['filename']="common.htm";
$z[2]=Array("include","",511,548);
$z[2][4]['filename']="header.htm";
$z[3]=Array("list","\n\n			<div class=\"panel\">				\n\n		        <div class=\"panel-body\">\n\n		        	<h3 style=\"background:url('/templets/bootstrap/images/document.png') no-repeat;padding-left:30px;\"><a href='[field:arcurl/]'>[field:title/]</a></h3>\n\n		            <p>[field:description/]...</p>\n\n		            <h5>标签：[field:id function=GetTags(@me)/]</h5>\n		        </div>\n\n		    </div>    \n\n			",689,1116);
$z[3][4]['pagesize']="12";
$z[3][4]['titlelen']="80";
$z[4]=Array("prenext","",1226,1252);
$z[4][4]['get']="pre";
$z[5]=Array("prenext","",1289,1316);
$z[5][4]['get']="next";
$z[6]=Array("include","",1535,1572);
$z[6][4]['filename']="footer.htm";

?>