<?php
$z[0]=Array("arclist","[field:pubdate function=strftime('%Y-%m-%d',@me)/]",157,270);
$z[0][4]['row']="1";
$z[0][4]['titlelen']="24";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("channel","\r\n<url>\r\n  <loc>http://www.flypeng.com[field:typelink /]</loc>\r\n  <changefreq>daily</changefreq>\r\n  <priority>0.8</priority>\r\n</url>\r\n",352,535);
$z[1][4]['row']="23";
$z[1][4]['type']="top";
$z[2]=Array("arclist","\r\n<url>\r\n   <loc>http://www.flypeng.com[field:arcurl/]</loc>\r\n   <lastmod>[field:pubdate function=strftime('%Y-%m-%d',@me)/]</lastmod>\r\n   <changefreq>monthly</changefreq>\r\n   <priority>0.5</priority>\r\n</url>\r\n",537,801);
$z[2][4]['row']="2000";
$z[2][4]['orderby']="pubdate";

?>